version: "3.8"

services:
  steganogan:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: ["steganogan", "--help"]
